### ISSUE TITLE
Proper format for Resource Pool?

### ISSUE THREAD

**Issue by dpeterka** [ezrapagel/knife-vsphere#29] opened 2012-12-17 17:48 UTC
Get a list:
knife vsphere pool list

From the list we will try something with no spaces or other funky:
ResourcePool: Cluster01/Resources/VDI

knife vsphere vm clone autonfs ... --resource-pool "Cluster01/Resources/VDI" ....

Returns error as do variations on the tree (VDI, "VDI", Resources/VDI etc. etc):

no such pool Cluster01/Resources/VDI while looking for Resources
no such pool Resources/VDI while looking for Resources
no such pool VDI while looking for Resources

Is this the correct format?

knife --version
Chef: 10.16.2

gem list --local knife-vsphere
knife-vsphere (0.3.0)

** mis-typed usage example on first post.  Corrected.

**Comment by DennisBP** [comment] 2015-04-23 15:36
The problem is solved, please close this issue. :relaxed:

cc / @ezrapagel

**Closed** 2015-04-23 15:38 UTC
