### ISSUE TITLE
Unable to create a new VM (moans about template)

### ISSUE THREAD

**Issue by swade1987** [ezrapagel/knife-vsphere#139] opened 2015-01-13 14:42 UTC
I am running the following command:

knife vsphere vm clone chef-test -f Templates --template MSDN-WIN2012R2Core --bootstrap true --run-list "role[windows_server_2012_r2]" 

See an image of my vSphere Web Client below 

![capture](https://cloud.githubusercontent.com/assets/594451/5722200/1c02222a-9b32-11e4-8edb-adf8e24d9d40.PNG)

I receive the following error message: "No such folder Templates while looking for Templates"

However, if I run "knife vsphere templates list" it can't find anything.

Any help will be much appreciated.

**Comment by troyready** [comment] 2015-01-13 17:19
That folder option (-f) should be used with vsphere folders (like the folder I have in the screenshot below). If your template isn't in a folder, drop the option.

![screenshot from 2015-01-13 09 11 05](https://cloud.githubusercontent.com/assets/1806418/5725021/74d4019e-9b04-11e4-9258-ed031c963da6.png)

**Comment by swade1987** [comment] 2015-01-13 19:57
Hi Troy,

I managed to get that sorted, however I am now experiencing another problem.

See here - http://stackoverflow.com/questions/27926043/knife-vsphere-issue-cloning-windows-vm

If you could help me it would be much appreciated.

Regards

Steve



On 13 Jan 2015, at 17:19, Troy Ready <notifications@github.com<mailto:notifications@github.com>> wrote:


That folder option (-f) should be used with vsphere folders (like the folder I have in the screenshot below). If your template isn't in a folder, drop the option.

[screenshot from 2015-01-13 09 11 05]<https://cloud.githubusercontent.com/assets/1806418/5725021/74d4019e-9b04-11e4-9258-ed031c963da6.png>

**Comment by troyready** [comment] 2015-01-13 20:16
The correct answer is usually 'trust coderanger' :)

**Comment by swade1987** [comment] 2015-01-15 09:00
Hi Troy,

I managed to get first that hurdle however now the following happens ...

c:\chef-repo>knife vsphere vm clone chef-test -f TEMPLATES --template MSDN-WIN2012R2Core --cspec MSDNWIN2012CORE --bootstrap
true --run-list "role[windows_server_2012_r2]"
Cloning template MSDN-WIN2012R2Core to new VM chef-test
Finished creating virtual machine chef-test
Powered on virtual machine chef-test
Waiting for sshd..................

It takes absolutely ages to get to that point and then just hangs.

Do you require Windows Server and not the "core" edition to install Chef Client?

**Comment by troyready** [comment] 2015-01-15 18:03
The issue is that it's waiting for an SSH daemon to respond so that it can continue bootstrapping (this is the standard way to do it for *nix VMs), but Windows does not come bundled with an SSH daemon. You can either install on in your VM template, or disable the bootstrap option during VM cloning and then bootstrap the machine afterward using the `knife bootstrap windows winrm` command (this will require setting up WinRM on the image and/or customization spec)

**Comment by swade1987** [comment] 2015-01-15 18:06
Thanks for this, how do I go about installing an SSH daemon, I am not sure I follow you.

------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
077 3822 1296
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 15 Jan 2015, at 18:03, Troy Ready <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is that it's waiting for an SSH daemon to respond so that it can continue bootstrapping (this is the standard way to do it for *nix VMs), but Windows does not come bundled with an SSH daemon. You can either install on in your VM template, or disable the bootstrap option during VM cloning and then bootstrap the machine afterward using the knife bootstrap windows winrm command (this will require setting up WinRM on the image and/or customization spec)

**Comment by troyready** [comment] 2015-01-15 18:10
If you're not familiar with SSH now, don't start down that road (it's not typical in Windows environments).

Pursue a WinRM setup. Good overall info is available at https://docs.chef.io/plugin_knife_windows.html#requirements

**Comment by swade1987** [comment] 2015-01-15 18:16
What so I would create VMs directly from the template using PowerCLI and then run the bootstrap command as per your suggestion?

However, I noticed that the template itself already has winrm installed and running.

------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
077 3822 1296
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 15 Jan 2015, at 18:10, Troy Ready <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're not familiar with SSH now, don't start down that road (it's not typical in Windows environments).

Pursue a WinRM setup. Good overall info is available at https://docs.chef.io/plugin_knife_windows.html#requirements

**Comment by troyready** [comment] 2015-01-15 18:24
What I have done is:
1) Clone the VM using `knife vsphere vm clone` with the bootstrap flag set to false. Since its not bootstrapping, this is probably interchangeable with the equivalent use of vSphere PowerCLI
2) Bootstrap the system into chef using `knife bootstrap windows winrm`

There are a bunch of other ways you could approach it. Instead of step 2 above, you could bake the Chef validation key into your VM image and have it automatically run chef client on first boot, etc. However, having WinRM configured is convenient for later use anyway so I'd say it's worth pursuing.

**Comment by swade1987** [comment] 2015-01-15 18:26
Awesome thanks, I will give that a go tomorrow, many thanks.

Also, whilst we are still speaking is their a recommended way of being able to deploy NuGet packages to Nodes using Chef?

------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
077 3822 1296
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 15 Jan 2015, at 18:24, Troy Ready <notifications@github.com<mailto:notifications@github.com>> wrote:


What I have done is:
1) Clone the VM using knife vsphere vm clone with the bootstrap flag set to false. Since its not bootstrapping, this is probably interchangeable with the equivalent use of vSphere PowerCLI
2) Bootstrap the system into chef using knife bootstrap windows winrm

There are a bunch of other ways you could approach it. Instead of step 2 above, you could bake the Chef validation key into your VM image and have it automatically run chef client on first boot, etc. However, having WinRM configured is convenient for later use anyway so I'd say it's worth pursuing.

**Comment by troyready** [comment] 2015-01-15 18:34
I don't know of any 'native' support currently or coming quickly down the pipeline. You can seek more advice on it in #chef on Freenode IRC.

**Comment by swade1987** [comment] 2015-01-28 10:14
Hi Troy.


I have just started on this, I have run the following command ....


knife vsphere vm clone chef-test -f TEMPLATES --template MSDN-WIN2012R2Core --cspec MSDNWIN2012CORE --bootstrap false --start


However the following is displayed ...


Cloning template MSDN-WIN2012R2Core to new VM chef-test
Finished creating virtual machine chef-test
Powered on virtual machine chef-test
Waiting for sshd...


It just hangs on this, is this something wrong with the template itself?


Regards


Steve


------------------------------------
Steven Wade

Principal Consultant

Steven Wade Consulting Ltd

077 3822 1296

steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>

uk.linkedin.com/in/stevendavidwade/<https://www.linkedin.com/in/stevendavidwade>

________________________________

**Comment by troyready** [comment] 2015-01-28 17:34
I think my advice was partially bad before -- bootstrap is [disabled by default](https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L121-L124), so omit the bootstrap option from your command entirely and it should properly [skip the bootstrap code](https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L290-L298).

**Comment by swade1987** [comment] 2015-01-28 17:35
Hi Troy,

I am actually going to create a VM template with the Chef Client already pre-installed.

How having issues with not having an SSL certificate on my Chef Server box. 

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
077 3822 1296
steven@stevenwade.co.uk <mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/ <http://uk.linkedin.com/in/stevendavidwade/>

**Comment by troyready** [comment] 2015-01-28 17:39
Yeah, that can be a bit of a pain, but manageable even with the cert autogenerated by the chef-server.

Feel free to pop in #chef on Freenode IRC if you run into any issues with it -- there's quite a bit of community experience in dealing with SSL certs, so you have a good chance of getting good help there.

**Comment by swade1987** [comment] 2015-01-28 17:42
Hi Troy,

Thanks for that.

I think i may need to re-install Chef Server on a new instance of RHEL.

Do you have a guide you would recommend?

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
077 3822 1296
steven@stevenwade.co.uk <mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/ <http://uk.linkedin.com/in/stevendavidwade/>

**Comment by troyready** [comment] 2015-01-28 17:49
In my experience the official chef.io documentation is pretty good on that. Because of the multiple installation options, the layout is a little weird (e.g., the real instructions for a single server setup are 'buried' under a link to a single server install), but the instructions themselves are good.

I'd recommend closing this GitHub issue if you're not having any more issues with knife-vsphere. Feel free to hit me up on IRC though if I can be of any more help with Chef.

**Closed** 2015-01-29 11:10 UTC
