### ISSUE TITLE
chef version conflict

### ISSUE THREAD

**Issue by sfiggins** [ezrapagel/knife-vsphere#20] opened 2012-07-23 15:49 UTC
I got a version conflict when installing this on a system with 10.12.0.  Gem would install chef 0.10 as well and that made knife very unhappy.   

I got around this by changing the chef version number in the gemspec and generating a new gem to use.  So far things appear to be working ok with 10.12.0.   Are you aware of any differences that have kept you from bumping the version in the gemspec?

**Comment by DennisBP** [comment] 2015-04-23 15:38
The problem is also solved, please close this issue. :wink:

cc / @ezrapagel

**Closed** 2015-04-23 21:22 UTC
