### ISSUE TITLE
Cannot manage VMs that are in vApps

### ISSUE THREAD

**Issue by MattMencel** [ezrapagel/knife-vsphere#25] opened 2012-10-19 15:32 UTC
If VMs are in a vApp....it doesn't look like they can be managed with knife vsphere.  They don't appear with all VMs using this command.

    knife vsphere vm list -r

They cannot be managed using this command because VMs in the vApp don't appear in the parent folder.

    $ knife vsphere vm state testVM -f "Test and Dev"
    VM testVM not found
    $ knife vsphere vm state testVM -f "Test and Dev//vAppTest"
    no such folder Test and Dev/vAppTest while looking for vAppTest

**Comment by swalberg** [comment] 2015-05-20 19:56
This seems to be a duplicate of #96? Do you have any updates?

I think I'll close this and we can work out of #96. Thanks.

**Closed by swalberg** 2015-05-20 19:56 UTC
